openapi: 3.0.0
info:
  title: Test API
  description: |
    This is a test API specification
    <!-- Embedded test comment -->
  version: 1.0.0
paths:
  /test:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: OK
