swagger: '2.0'
info:
  title: Example YAML.spec
  description: |
    <math><foo-test><mi><li><table><foo-test><li></li></foo-test><a>
        <style>
          <! ${
        </style>
        }
        <foo-b id="><img src=x id="</img><img src=x ontoggle="alert(String.fromCharCode(88,83,83))'>">pwned</foo-b>
      </a></table></li></mi></foo-test></math>
paths:
  /phished:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts






