swagger: '2.0'
info:
  title: Example YAML.spec
  description: |
    <math><table><tr><td><svg><a><animate onbegin=alert(1) attributeName=x dur=1s repeatCount=indefinite></a></svg></td></tr></table></math>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts



