swagger: '2.0'
info:
  title: Example YAML.spec
  description: |
    <foo-x id="><svg><script>alert(1337)</script>">
paths:
  /phished:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts




