swagger: "2.0",
info: 
  title: "Swagger Sample App",
  description: "Please to click Terms of service"
  termsOfService: "javascript:alert(1)"
  contact: 
    name: "API Support",
    url: "javascript:alert(1)",
    email: "javascript:alert(1)"
  version: "1.0.1"
