swagger: '2.0'
info:
  title: Example YAML.spec
  description: |
    <h1 style="color:red;font-family:sans-serif;">This has been poisoned</h1>
paths:
  /phished:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
